server:
  port: 8083
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/microservices

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: RATING-SERVICE

  config:
    import: configserver:http://localhost:8085
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#okta configuration
okta:
  oauth2:
    issuer: https://dev-81131548.okta.com/oauth2/default
    audience: api://default
